experiment:
  type: rl
  exp_dir: "${DATA}/runs/expert_iteration_llm_2x_l40s"
  dataset_size: 0
  total_rounds: 10
  temperature: 1.0
  epochs: 1
  sampler: Sampler_base
  conjecture_multiplier: 10
  llm:
    base_model: "${DATA}/runs/sft_deepseek_coder_1.3b_l40s/models/moy6hpa5/step-1004"
    dataset_config: "RL/dataset_configs/stp_llm_deltaproof_rl_1_8.json"
    attempts_per_round: 4800
    conjecture_attempts: 16
    conjecture_fraction: 0

training:
  max_tune_length: 2048
  trust_remote_code: true

  trainer:
    ray:
      auto_start_cluster: false
    tracker:
      type: wandb
      entity: s204164-danmarks-tekniske-universitet-dtu
      project: alpha-STP
      name: llm-expert-2x-l40s
      tags: [LLM, expert-iteration, 2x-L40S]

    seed: 0
    mp: p=f32,c=bfloat16
    train_batch_size: 32
    steps_per_eval: 100
    model_axis_size: 1
    tensor_parallel_axes: [mlp, heads]
    per_device_eval_parallelism: 16
    per_device_parallelism: 16

  eval_on_first_step: false

  optimizer:
    learning_rate: 6.25e-6
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.95
    epsilon: 1.0e-5
    max_grad_norm: 1.0
    lr_schedule: cosine
    stable: 0.0
    cooldown: 0.0
    min_lr_ratio: 1.0
